image: python:latest

stages:
    - build
    - test


build-job:
    stage: build
    script:
        - echo "Creating database..."
        - mkdir -p $CI_PROJECT_DIR/resources/data/ && touch $CI_PROJECT_DIR/resources/data/data.db
        - echo "Database created"
    
test-db:
    stage: test
    script:
        - test -f ./resources/data/data.db && echo "Test db passed."