image: python:latest

stages:
    - build
    - test

pre-job:
    stage: .pre
    script:
        - echo "iam pre job"
        - apt-get install tree

build-job:
    stage: build
    script:
        - echo "Building..."
        - tree
test-db:
    stage: test
    script:
        - test -f $CI_PROJECT_DIR/resources/data/data.db && echo "Test db passed."
