image: python:latest

stages:
    - deploy

download-SP500-data:
    stage: deploy
    only:
        - main
    script:
        - >
            if [ "$automatic_run" == "true" ] ;
            then
            pip3 install -r resources/requirements/requirements.txt;
            python3 download_SP_500_data.py;
            fi
