image: python:latest

stages:
    - build
    - test

pre-job:
    stage: .pre
    script:
        - echo "iam pre job"

build-job:
    stage: build
    script:
        - echo "Building... env $CI_ENVIRONMENT_NAME"
test-db:
    stage: test
    script:
        - test -f $CI_PROJECT_DIR/resources/data/data.db && echo "Test db passed."
