image: python:latest

stages:
    - build
    - deploy

pre-job:
    stage: .pre
    script:
        - echo "iam pre job"

build-job:
    stage: build
    script:
        - echo "Building..."

download-SP500-data:
    stage: deploy
    script:
        - >
            if ["$automatic_run" == "true"] 
            then
            pip3 install -r resources/requirements/requirements.txt
            python3 download_SP_500_data.py
            fi
                


